### ISSUE TITLE
Bug images registration 

### ISSUE THREAD

**Issue by olivier469110** [marcnol/pyHiM#109]
I encountered 2 bugs in images registration 

1- 

I run pyHiM using the folowing commande : 

pyHiM.py -F .

During the process, pyHiM should produce a file called alignImages_block3D.dat saved in the alignImages folder. In my case, pyHiM produces a file called _block3D.dat at the root of the analyzed folder.  In that way 3D registration is not applied.

2-

I also encountered an other problem by executing this command :

pyHiM.py -C  filter_localizations,register_localizations

pyHiM should load the a file called : segmentedObjects_barcode.dat in the folder segmentedObjects and apply registration in 2D. However, if the string "3D" is present in the path of the analyzed folder (like Experiment_6_Olivier_Marie_seqRNA_HiM_Pancreas/Analysis_3D_180822/002_ROI_Links), it understands that it should apply the 3D recording instead of 2D and crashes.

**Comment by marcnol** [comment]
Olivier, can you test the fix of the second issue in branch 'fix_issue/109' ?

**Comment by olivier469110** [comment]
It's fixed with that version

**Comment by marcnol** [comment]
now register_localization exits if dict of 3D corrections is not found..
See [c1bc3d4](https://github.com/marcnol/pyHiM/pull/111/commits/c1bc3d4c507c1b48dae594204bd8d23f36544f2f) and [00aedcd](https://github.com/marcnol/pyHiM/pull/111/commits/00aedcdf94b7ca04d1da31aa02899dfb8f0d7249) for commits fixing these issues

**Comment by marcnol** [comment]
fixed merged into dev branch
