### ISSUE TITLE
Problems with Darwin - Not running with multiple threads - Development branch

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#117]
I have tried to launch a pyHiM analysis on the data I acquired last week, but something strange is happening.
I launched the following command line :
pyHiM.py -C makeProjections,alignImages,appliesRegistrations,alignImages3D,segmentMasks --threads 10

The problem is that it kind of stops after creating the different folders (alignImages, zproject ...).
It does not crash, just it does not advance.
I waited for 1h30, still nothing.
Even though nothing is really happening it uses a lot of workers.
At some point, it gave the impression that all darwin threads were used (visualized with "htop" command line).
Nothing like this happened to me before.
I also tried to launch it with Olivier's session in Darwin, and we got the same result.
Now, it works but only if I do not precise the number of threads.
The command line used is the following : 
pyHiM.py -C makeProjections,alignImages,appliesRegistrations,alignImages3D,segmentMasks

This problem happened on the development branch.

When we switch to the master branch, it runs with the threads.
Command line : pyHiM.py -C makeProjections,alignImages,appliesRegistrations,alignImages3D,segmentMasks --threads 10
Although, it creates a cluster with only 4 threads.

**Comment by marcnol** [comment]
this has to do with resources and is not related to pyHiM
