### ISSUE TITLE
Problems on darwin and lifou when pyHiM running with threads

### ISSUE THREAD

**Issue by XDevos** [marcnol/pyHiM#119]
On darwin:
- Leaked semaphore
[darwin_leaked_semaphore.log](https://github.com/marcnol/pyHiM/files/10578252/darwin_leaked_semaphore.log)
- Possible memory leak
[darwin_memory_leak.log](https://github.com/marcnol/pyHiM/files/10578253/darwin_memory_leak.log)
- Timeout register localizations
[darwin_timeout_register_localizations.log](https://github.com/marcnol/pyHiM/files/10578254/darwin_timeout_register_localizations.log)

On lifou:
- Connection to lifou closed (TimeoutError)
[lifou_closed.log](https://github.com/marcnol/pyHiM/files/10578255/lifou_closed.log)

Commands used for runs:
`pyHiM.py -C makeProjections,alignImages,alignImages3D,segmentMasks3D,segmentSources3D -T 10`
`pyHiM.py -C filter_localizations,register_localizations,build_traces,build_matrix -T 10`

Data paths:
Lifou = `/mnt/grey/DATA/users/xdevos/testHiM/speedtest/on_lifou/parallel/dim3`
Darwin = `/DATA/xdevos_speedtest/on_darwin/parallel/dim3`

**Comment by marcnol** [comment]
Do not mix issues of pyHiM with infrastructure.

Lifou  goes to suspend mode--> needs to fix. As for darwin, do you reproduce this in the master branch?
