### ISSUE TITLE
make drift tolerance anisotropic

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#122]
currently the tolerance to apply or not a local drift is based on an isotropic threshold (typically 1px). Because a small tolerance needs to be set for xy, this is not the case for z which could include focal plane drift of more than 1 plane that can be compensated and should be tolerated. Thus, it would make sense to provide an anisotropic threshold, such as (3,1,1).

**Comment by MarionBardou** [comment]
(pyHiM_refact) bardou@darwin:/mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy$ pyHiM.py -C filter_localizations,register_localizations,build_traces,build_matrix

$ Parameters loaded:
	rootFolder		/mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy
	stardist_basename	None
	threads			1
	parallel		False
	cmd			['filter_localizations', 'register_localizations', 'build_traces', 'build_matrix']


$ Model parameters file saved to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/infoList_model.json
$ Parameters file read: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/infoList.json
$ Started logging to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/HiM_analysis01042023_151817.log
$ labels to process: ['fiducial', 'barcode', 'DAPI', 'RNA', 'mask']

$ Model parameters file saved to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/infoList_model.json
$ Parameters file read: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/infoList.json
Amended 0 keys for fiducial
--------------------------------------------------------------------------
>                  Analyzing label: fiducial           
--------------------------------------------------------------------------


$ Model parameters file saved to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/infoList_model.json
$ Parameters file read: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/infoList.json
Amended 33 keys for barcode
--------------------------------------------------------------------------
>                  Analyzing label: barcode           
--------------------------------------------------------------------------

====================filter_localizations====================

$ folders read: 1
> Processing Folder: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy
$ Successfully loaded barcode localizations file: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/segmentedObjects/segmentedObjects_barcode.dat
Number of barcodes read from barcode_map: 25
Unique Barcodes detected: [  1   2   3   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21
  23  24  26  27  28 639 708]
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/segmentedObjects/segmentedObjects_barcode_version_13_.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 16

$ rois detected: 1
$ Minimum flux: 10
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27500/27500 [00:00<00:00, 799058.95it/s]
$ Removed 2697 barcode localizations from table out of 27500.
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/segmentedObjects/segmentedObjects_barcode.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 16
$ Successfully loaded barcode localizations file: /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/segmentedObjects/segmentedObjects_3D_barcode.dat
Number of barcodes read from barcode_map: 25
Unique Barcodes detected: [  1   2   3   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21
  23  24  26  27  28 639 708]
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/segmentedObjects/segmentedObjects_3D_barcode_version_13_.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 16

$ rois detected: 1
$ Minimum flux: 0.1
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23801/23801 [00:00<00:00, 334076.13it/s]
$ Removed 0 barcode localizations from table out of 23801.
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/rut/016__ROI_anisotropy/segmentedObjects/segmentedObjects_3D_barcode.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 16
Traceback (most recent call last):
  File "/home/bardou/Repositories/pyHiM/src/pyHiM.py", line 150, in <module>
    main()
  File "/home/bardou/Repositories/pyHiM/src/pyHiM.py", line 116, in main
    fc.register_localizations(current_param, label)
  File "/home/bardou/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 351, in register_localizations
    register_localizations_instance = RegisterLocalizations(current_param)
  File "/home/bardou/Repositories/pyHiM/src/matrixOperations/register_localizations.py", line 60, in __init__
    tolerance_drift = (tolerance_drift,tolerance_drift,tolerance_drift)
UnboundLocalError: local variable 'tolerance_drift' referenced before assignment

**Comment by MarionBardou** [comment]
(pyHiM_refact) bardou@darwin:/mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter$ pyHiM.py -C filter_localizations,register_localizations,build_traces,build_matrix

$ Parameters loaded:
	rootFolder		/mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter
	stardist_basename	None
	threads			1
	parallel		False
	cmd			['filter_localizations', 'register_localizations', 'build_traces', 'build_matrix']


$ Model parameters file saved to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/infoList_model.json
$ Parameters file read: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/infoList.json
$ Started logging to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/HiM_analysis13042023_142609.log
$ labels to process: ['fiducial', 'barcode', 'DAPI', 'RNA', 'mask']

$ Model parameters file saved to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/infoList_model.json
$ Parameters file read: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/infoList.json
Amended 0 keys for fiducial
--------------------------------------------------------------------------
>                  Analyzing label: fiducial           
--------------------------------------------------------------------------


$ Model parameters file saved to: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/infoList_model.json
$ Parameters file read: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/infoList.json
Amended 33 keys for barcode
--------------------------------------------------------------------------
>                  Analyzing label: barcode           
--------------------------------------------------------------------------

====================filter_localizations====================

$ folders read: 1
> Processing Folder: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter
$ Successfully loaded barcode localizations file: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/segmentedObjects/segmentedObjects_barcode.dat
Number of barcodes read from barcode_map: 25
Unique Barcodes detected: [11 12 13 27 28 29 30 31 33 34 35 37 38 40 41 42 43 44 45 46 47 48 49 50
 51]
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/segmentedObjects/segmentedObjects_barcode_version_4_.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 2

$ rois detected: 1
$ Minimum flux: 10
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18527/18527 [00:00<00:00, 789473.44it/s]
$ Removed 0 barcode localizations from table out of 18527.
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/segmentedObjects/segmentedObjects_barcode.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 2
$ Successfully loaded barcode localizations file: /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/segmentedObjects/segmentedObjects_3D_barcode.dat
Number of barcodes read from barcode_map: 25
Unique Barcodes detected: [11 12 13 27 28 29 30 31 33 34 35 37 38 40 41 42 43 44 45 46 47 48 49 50
 51]
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/segmentedObjects/segmentedObjects_3D_barcode_version_4_.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 2

$ rois detected: 1
$ Minimum flux: 0.1
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18484/18484 [00:00<00:00, 340470.50it/s]
$ Removed 0 barcode localizations from table out of 18484.
Saving output table as /mnt/grey/DATA/AnalyzedData_2023/Experiment_16_Sandrine_Marion_pupa_WT_Mutant/Mutant/002_ROI_test_filter/segmentedObjects/segmentedObjects_3D_barcode.dat ...

$ rois detected: 1
Plotting barcode localization map for ROI: 2
Traceback (most recent call last):
  File "/home/bardou/Repositories/pyHiM/src/pyHiM.py", line 150, in <module>
    main()
  File "/home/bardou/Repositories/pyHiM/src/pyHiM.py", line 116, in main
    fc.register_localizations(current_param, label)
  File "/home/bardou/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 351, in register_localizations
    register_localizations_instance = RegisterLocalizations(current_param)
  File "/home/bardou/Repositories/pyHiM/src/matrixOperations/register_localizations.py", line 60, in __init__
    tolerance_drift = (tolerance_drift,tolerance_drift,tolerance_drift)
UnboundLocalError: local variable 'tolerance_drift' referenced before assignment
