### ISSUE TITLE
Stripe KDtree - absence of traces

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#127]
A strange stripe can appear on ROIs at different positions and it can have different sizes.
This stripe appears as a region without any trace.
It is present only on the KDtree traces image and not in the mask or the DAPI.
It does not appear on the localization either.

**Comment by MarionBardou** [comment]
path to following data : /mnt/grey/DATA/AnalyzedData_2023/Experiment_7_Marion_Brains_OK107/sNPF/028_ROI/

**Trace_3D_barcode_KDtree_ROI:28_traces_XYZ_ROI28.png**
![image](https://user-images.githubusercontent.com/66315316/230121750-d9e9e92f-a0e6-473e-9c27-ce199399b86b.png)

**Trace_3D_barcode_mask:mask1_ROI:28_traces_XYZ_ROI28.png**
![image](https://user-images.githubusercontent.com/66315316/230122415-4e0921c4-1148-49ff-a634-7af97c979c42.png)

**segmentedObjects_3D_barcode_barcode_localizations_ROI28.png**
![image](https://user-images.githubusercontent.com/66315316/230122914-3c5046f4-9fcb-427f-a89e-09a438dfae17.png)

**Comment by marcnol** [comment]
Agree, I  just see the same thing in a different data set. It seems to only appear for KDtree not for DAPI masking.
Need to look at this!
