### ISSUE TITLE
processSNDchannel.py - DAPI mask

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#129]
While running analysis for Sandrine on the segments, I realized that processSNDchannel.py matches the previously defined SND mask and a DAPI mask.

here is part of the terminal :

====================processesUserMasks====================

folders read: 1
-------> Processing Folder: .
About to process 1 files

-----> Processing: ./segmentedObjects/scan_001_DAPI_019_ROI_converted_decon_ch02_2d_registered_SNDmask_TS5.npy

Will search masks in: ./segmentedObjects/scan_001_DAPI_019_ROI_converted_decon_ch00_Masks.npy

Will attemp to match masks from: ./segmentedObjects/scan_001_DAPI_019_ROI_converted_decon_ch02_2d_registered_SNDmask_TS5.npy
Matched DAPI and SND masks: 
 SND: ./segmentedObjects/scan_001_DAPI_019_ROI_converted_decon_ch02_2d_registered_SNDmask_TS5.npy
 DAPI: ./segmentedObjects/scan_001_DAPI_019_ROI_converted_decon_ch00_Masks.npy

**Comment by marcnol** [comment]
not sure what you mean. Can you clarify?

**Comment by XDevos** [comment]
I close this issue as won't fix, we have insufficient information to understand the problem.
