### ISSUE TITLE
output file for DAPI mask incorrect

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#137]
the output file is:
`scan_001_DAPI_001_ROI_decon_ch01._Masks.npy`

but it should be 

`scan_001_DAPI_001_ROI_decon_ch01_Masks.npy`

**Comment by marcnol** [comment]
I did a fix in branch [issue/137](https://github.com/marcnol/pyHiM/tree/issue/137)
Xavier, can you test before we commit to dev?

**Comment by XDevos** [comment]
I update the file name on the pyhim-small-dataset side.
It's merged on dev.
