### ISSUE TITLE
Forbid pyHiM execution on multiple ROIs at the same time

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#142]
Running in a folder with multiple ROIs seems to not work anymore.
The dict of global corrections is there:
`alignImages/alignImages.json`
however it only contains keys for one of the ROIs. Is it overwritten and not appended?

**Comment by marcnol** [comment]
for the moment I split by ROI as the problem persists. I think it is overwriting the dictionary of corrections when it performs analysis for different ROIs.

**Comment by XDevos** [comment]
User should use a bash script (for example) to run pyHiM on each ROI. A bash script template or generator will be provide.
