### ISSUE TITLE
Uniqueness of label in SNDassignedCells.ecsv not enforced

### ISSUE THREAD

**Issue by mg42** [marcnol/pyHiM#16]
When processSNDchannel.py --addMask <label> is run and <label> is already in SNDassignedCells.ecsv, no warning is given, and the newly selected cells are just appended to the end of SNDassignedCells.ecsv

This might pose a problem of the old and new masks for the same <label> differ.

**Comment by marcnol** [comment]
is this really relevant to the new versions of pyHiM?

**Comment by marcnol** [comment]
is this really relevant to the new versions of pyHiM?
