### ISSUE TITLE
bug when running threads in dev

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#161]
when running:
`pyHiM.py -C makeProjections,alignImages,appliesRegistrations --threads 20`

in `darwin:/mnt/grey/DATA/rawData_2023/Experiment_78_Marie_Christel_Julian_Droso_Late_embryos_confocal_2/Analysis/003'

I get:

```
! [INFO] Folder '/mnt/grey/DATA/rawData_2023/Experiment_78_Marie_Christel_Julian_Droso_Late_embryos_confocal_2/Analysis/003/zProject' already exists.
Traceback (most recent call last):
  File "/home/marcnol/Repositories/pyHiM/src/pyHiM.py", line 154, in <module>
    main()
  File "/home/marcnol/Repositories/pyHiM/src/pyHiM.py", line 70, in main
    pipe.run()
  File "/home/marcnol/Repositories/pyHiM/src/core/function_caller.py", line 154, in run
    client.forward_logging()
AttributeError: 'Client' object has no attribute 'forward_logging'
```

**Comment by XDevos** [comment]
I find the bug, the version of dask[distributed] install by the environment.yml is the v2021.10.0.
But But the logger and forward_logging just doesn't exist in this version, you need to make a `pip install -U distributed`.

**Comment by XDevos** [comment]
e6458fbb7063c5a03429eaad83b1ba56bcd92699

**Comment by marcnol** [comment]
cool!
