### ISSUE TITLE
trace_to_matrix.py - missing module

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#185]
I just did a git pull on development and I think a dependency changed.

Now, when I try to run "trace_to_matrix.py", I get the following error : 
"
(pyHiM_refact) bardou@darwin:/mnt/grey/DATA/users/Marion/Hi-M_analysis_Droso_brain/rut/non_OK107/3D_projected/Combined_exp_32_53_filt/15bc_min$ trace_to_matrix.py --help
Traceback (most recent call last):
  File "/home/bardou/Repositories/pyHiM/src/postProcessing/trace_to_matrix.py", line 23, in <module>
    from matrixOperations.build_matrix import BuildMatrix
  File "/home/bardou/Repositories/pyHiM/src/matrixOperations/build_matrix.py", line 39, in <module>
    from core.parameters import get_dictionary_value
  File "/home/bardou/Repositories/pyHiM/src/core/parameters.py", line 14, in <module>
    from dataclasses_json import CatchAll, LetterCase, Undefined, dataclass_json
ModuleNotFoundError: No module named 'dataclasses_json'
"

**Comment by MarionBardou** [comment]
I forgot about that email.
It is my fault.
Sorry for the disturbance

**Comment by XDevos** [comment]
For the future and others:
In this error case, you usually have to do a "pip install <module_name>" like `pip install dataclasses_json`.
