### ISSUE TITLE
datamanager fails to recognize file name in folders

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#206]
ValueError: Filename: Trace_3D_barcode_mask:mask1_ROI:0_Matrix_Nmatrix
Doesn't match with regex: scan_(?P<runNumber>[0-9]+)_(?P<cycle>[\w|-]+)_(?P<roi>[0-9]+)_ROI_converted_decon_(?P<channel>[\w|-]+)

when running 
$ pyHiM.py -C build_matrix

at 
/mnt/grey/DATA/AnalyzedData_2023/Experiment_47_Marion_c739_sNPF_rut/rut_c739_rep1/000_ROI

**Comment by XDevos** [comment]
It's fixed and merged in development.
