### ISSUE TITLE
Error while trying to run segmentation process on mask1

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#27]
I tried to launch an analysis with the fiducial as "mask1".
During the segmentation of mask1, it stopped and apparently it was coming from two different errors.
[mask_error_pyHiM.txt](https://github.com/marcnol/pyHiM/files/8041638/mask_error_pyHiM.txt)
One seems to be related to utils.py, the other one to stardist.
Just in case, I have updated photutils and stardist packages but it does not seem to fix it.

**Comment by marcnol** [comment]
sounds like you were providing stardist a 3D model and asking it to segment in 3D. Check networks used in `infoList.json`:
```
"stardist_network": "PSF_2D_stardist_19032021_single_loci",
"stardist_network3D": "PSF_3D_stardist_20210618_simu_deconvolved_thresh_0_01",
```
the former should point to a 2D network the latter to a 3D network. 
See `/docs/AI_networks.md` for more info!
