### ISSUE TITLE
Problem to change RT fiducial

### ISSUE THREAD

**Issue by Christof-H** [marcnol/pyHiM#29]
We cannot change the RT of the fiducial with the changeRT_infolist.py script because there is no more infoList_fiducial.json (infoList.json now).
I fixed the problem by manually changing the RT fiducial in infoList.json

**Comment by marcnol** [comment]
I will ask Xavier and JB to on a GUI to check and set all the parameters in `infoList.json`. Let's wait for this to happen. In the meanwhile, probably best done by hand.

**Comment by marcnol** [comment]
this script is defunct and superseded by the infoList GUI
