### ISSUE TITLE
Path to "postProcessing" folder in "bashrc"

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#31]
With Olivier, we realized that the current lines that need to be added to the "bashrc" are not working when we need to run a python process in the folder "postProcessing".

The current lines look like this (in the Installing_pyHiM file) :
`export PATH="$PATH:$HOME/Repositories/pyHiM/src:$HOME/Repositories/pyHiM/src/fileProcessing"
export PYTHONPATH="$HOME/Repositories/pyHiM/src"

export MPLBACKEND=agg`

For us, it works when it looks like that :
`export PATH="$PATH:/home/bardou/Repositories/pyHiM/src:/home/bardou/Repositories/pyHiM/src/fileProcessing:/home/bardou/Repositories/pyHiM/src/postProcessing"
export PYTHONPATH="/home/bardou/Repositories/pyHiM/src"

export MPLBACKEND=agg`

**Comment by marcnol** [comment]
What you need to do is to create symbolic links using `ln -s` to the files you will be using from the command line to avoid needing to include more and more folders into your PATH.
This can be done for instance by doing:
`ln -s /home/marcnol/Repositories/pyHiM/sources/postProcessing/trace_selector.py /home/marcnol/bin/trace_selector`
this will create a ln of `trace_selector.py`in the `~/bin`folder which is the only one you need to put in your $PATH within `.bashrc`
