### ISSUE TITLE
ProcessSNDchannel.py error with 3D segmentation of mask1

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#33]
Just out of information, I did the 3D segmentation of my fiducial and it works well.
Thus, I wanted to build the matrices for each segment of pupa.
I tried to run "processSNDchannel.py" on the data (after I had run the "processSegmentmask3D").
But it gives the following error :
[ProcessSNDchannel_error_pyHiM.txt](https://github.com/marcnol/pyHiM/files/8090810/ProcessSNDchannel_error_pyHiM.txt)

If I run "processSNDchannel.py" (without, before, running "processSegmentmask3D"), it works fine.

**Comment by marcnol** [comment]
A bug fix will be coming. 

In the meantime, worth looking at the script `trace_selector`. See section 7 of `running_pyHiM`.

**Comment by marcnol** [comment]
The bug report indicates that you have a TIF file in your rootFolder that does not comply with the expected format. Please revise this list and amend or remove the offending file!
