### ISSUE TITLE
Barcode segmentation

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#38]
Barcodes end up segmented just like DAPI masks.
[HiM_analysis25022022_170221.log](https://github.com/marcnol/pyHiM/files/8162216/HiM_analysis25022022_170221.log)

**Comment by marcnol** [comment]
Please specify what you mean exactly

**Comment by XDevos** [comment]
I close this issue as won't fix, we have insufficient information to understand the problem.
