### ISSUE TITLE
Error_merging_processSNDchannel_files_with_processHiMmatrix

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#40]
I am trying to merge the matrices for each segments.
Here I tried to merge all TS5 segments.
Got the following error :
[Error_merging_processSNDchannel_files.txt](https://github.com/marcnol/pyHiM/files/8205861/Error_merging_processSNDchannel_files.txt)
Here is the path to the merging folder : /mnt/grey/DATA/AnalyzedData_2022/Experiment_4_Sandrine_Marion_pupa_HiRes_42nt/Merge_TS5

**Comment by marcnol** [comment]
it works for my version, commit: c46d065fb8f685694350c074cf2cd4df64265f99
HEAD -> compliance_apiFISH, origin/compliance_apiFISH

**Comment by marcnol** [comment]
I added some reporting + a condition that prevents this from happening. It all runs fine with this commit: f609b76485e59d090a0bcdcbbc6e7201c6ed3b21
