### ISSUE TITLE
Install document

### ISSUE THREAD

**Issue by Christof-H** [marcnol/pyHiM#44]
1-impossible to install apiFISH repository on serveur with `git clone git@github.com:apiFISH/apiFISH.git`, but it was done with `https://github.com/apiFISH/apiFISH.git`
2-after apiFISH installation, the repository folder is apiFISH :  problem with instructions: 
cd $HOME/Repositories
git clone git@github.com:apiFISH/apiFISH.git
cd **apiFISH** && git checkout development at the place of cd apifish && git checkout development

**Comment by XDevos** [comment]
It's fixed on `refacto_doc` branch, update soon on `development` branch.
