### ISSUE TITLE
Error build_traces

### ISSUE THREAD

**Issue by MarionBardou** [marcnol/pyHiM#47]
I have an error related to the mask_ID while running build_traces.
The error shows up for mask1 and not for the DAPI
Here is my terminal with the error :

[Error_build_traces.txt](https://github.com/marcnol/pyHiM/files/8378662/Error_build_traces.txt)

**Comment by marcnol** [comment]
names of maskIDs need to follow the format: maskN where N is an integer.
please NEVER use "_" in mask names or RT names as "_" is used to break up the filename into keys.

**Comment by marcnol** [comment]
fixed in commit a777ba92dc000b626826c5759fda1dfb7adab32a
