### ISSUE TITLE
Problem during segmentSources3D

### ISSUE THREAD

**Issue by Christof-H** [marcnol/pyHiM#58]
Location RawData : /mnt/grey/DATA/AnalyzedData_2022/Experiment_13_Tof_tests/Images_deconvolved_sorted/sorted_by_ROI

Command : $ pyHiM.py -C makeProjections,alignImages,appliesRegistrations,segmentSources3D

TypeError: cannot perform reduce with flexible type

Here, the ouput during pyHiM analysis :
[error.txt](https://github.com/marcnol/pyHiM/files/8630240/error.txt)

**Comment by marcnol** [comment]
Xavier, was this fixed and merged to dev?
