### ISSUE TITLE
Duplicated localizations when running SegmentSources3D on multiple ROIs

### ISSUE THREAD

**Issue by jbfiche** [marcnol/pyHiM#70]
Running the source detection on two color data (the same RT but different ROIs):

pyHiM.py -C segmentSources3D

The segmentedObjects_3D_barcode.dat output file is containing a large number of repeated localizations. For example, out of the >4000 localizations detected for ROI1, ~7% are unique.

**Comment by marcnol** [comment]
seems similar to issue #23

**Comment by XDevos** [comment]
Since #181, pyHiM restricts execution to a single ROI.
so this problem shouldn't be encountered again.
