### ISSUE TITLE
Update `installation.sh` file

### ISSUE THREAD

**Issue by XDevos** [marcnol/pyHiM#96]
It work with big-fish repo, change to apifish.
May be we can change the python version and some unused dependencies.

**Comment by marcnol** [comment]
sure. Remove openCV?

**Comment by marcnol** [comment]
we should look into this and remove if openCV is actually not much used.  Replace by scikit-image

**Comment by XDevos** [comment]
File was removed on Jul 27, 2022 ?
See:
https://github.com/marcnol/pyHiM/commit/491caf4ccc6f85e2dc79ac5a57d7f0d594791a8b
